# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'changeinfo.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(745, 457)
        self.lbl_birthday1 = QtWidgets.QLabel(Dialog)
        self.lbl_birthday1.setGeometry(QtCore.QRect(170, 319, 141, 21))
        font = QtGui.QFont()
        font.setFamily("PT Serif")
        font.setPointSize(18)
        self.lbl_birthday1.setFont(font)
        self.lbl_birthday1.setObjectName("lbl_birthday1")
        self.lbl_depnum1 = QtWidgets.QLabel(Dialog)
        self.lbl_depnum1.setGeometry(QtCore.QRect(280, 9, 131, 21))
        font = QtGui.QFont()
        font.setFamily("PT Serif")
        font.setPointSize(18)
        self.lbl_depnum1.setFont(font)
        self.lbl_depnum1.setObjectName("lbl_depnum1")
        self.btn_save = QtWidgets.QPushButton(Dialog)
        self.btn_save.setGeometry(QtCore.QRect(160, 400, 181, 31))
        self.btn_save.setObjectName("btn_save")
        self.btn_cancel = QtWidgets.QPushButton(Dialog)
        self.btn_cancel.setGeometry(QtCore.QRect(420, 400, 181, 31))
        self.btn_cancel.setObjectName("btn_cancel")
        self.lbl_phone1 = QtWidgets.QLabel(Dialog)
        self.lbl_phone1.setGeometry(QtCore.QRect(170, 209, 141, 21))
        font = QtGui.QFont()
        font.setFamily("PT Serif")
        font.setPointSize(18)
        self.lbl_phone1.setFont(font)
        self.lbl_phone1.setObjectName("lbl_phone1")
        self.lbl_surname1 = QtWidgets.QLabel(Dialog)
        self.lbl_surname1.setGeometry(QtCore.QRect(170, 59, 91, 16))
        font = QtGui.QFont()
        font.setFamily("PT Serif")
        font.setPointSize(18)
        self.lbl_surname1.setFont(font)
        self.lbl_surname1.setObjectName("lbl_surname1")
        self.lbl_email1 = QtWidgets.QLabel(Dialog)
        self.lbl_email1.setGeometry(QtCore.QRect(170, 244, 91, 16))
        font = QtGui.QFont()
        font.setFamily("PT Serif")
        font.setPointSize(18)
        self.lbl_email1.setFont(font)
        self.lbl_email1.setObjectName("lbl_email1")
        self.lbl_patr1 = QtWidgets.QLabel(Dialog)
        self.lbl_patr1.setGeometry(QtCore.QRect(170, 119, 91, 16))
        font = QtGui.QFont()
        font.setFamily("PT Serif")
        font.setPointSize(18)
        self.lbl_patr1.setFont(font)
        self.lbl_patr1.setObjectName("lbl_patr1")
        self.lbl_name1 = QtWidgets.QLabel(Dialog)
        self.lbl_name1.setGeometry(QtCore.QRect(170, 89, 91, 16))
        font = QtGui.QFont()
        font.setFamily("PT Serif")
        font.setPointSize(18)
        self.lbl_name1.setFont(font)
        self.lbl_name1.setObjectName("lbl_name1")
        self.lineEdit_depnum = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_depnum.setGeometry(QtCore.QRect(410, 10, 113, 21))
        self.lineEdit_depnum.setObjectName("lineEdit_depnum")
        self.lineEdit_surname = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_surname.setGeometry(QtCore.QRect(330, 56, 261, 21))
        self.lineEdit_surname.setObjectName("lineEdit_surname")
        self.lineEdit_name = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_name.setGeometry(QtCore.QRect(330, 85, 261, 21))
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.lineEdit_patronymic = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_patronymic.setGeometry(QtCore.QRect(330, 116, 261, 21))
        self.lineEdit_patronymic.setObjectName("lineEdit_patronymic")
        self.lineEdit_phone = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_phone.setGeometry(QtCore.QRect(330, 208, 261, 21))
        self.lineEdit_phone.setObjectName("lineEdit_phone")
        self.lineEdit_email = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_email.setGeometry(QtCore.QRect(330, 241, 261, 21))
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.dateEdit = QtWidgets.QDateEdit(Dialog)
        self.dateEdit.setGeometry(QtCore.QRect(482, 316, 110, 24))
        self.dateEdit.setObjectName("dateEdit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Изменение информации"))
        self.lbl_birthday1.setText(_translate("Dialog", "Дата рождения"))
        self.lbl_depnum1.setText(_translate("Dialog", "Номер отдела"))
        self.btn_save.setText(_translate("Dialog", "Сохранить изменения"))
        self.btn_cancel.setText(_translate("Dialog", "Отменить"))
        self.lbl_phone1.setText(_translate("Dialog", "Номер телефона"))
        self.lbl_surname1.setText(_translate("Dialog", "Фамилия"))
        self.lbl_email1.setText(_translate("Dialog", "E-mail"))
        self.lbl_patr1.setText(_translate("Dialog", "Отчество"))
        self.lbl_name1.setText(_translate("Dialog", "Имя"))
