# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(747, 475)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 751, 496))
        self.tabWidget.setFocusPolicy(QtCore.Qt.TabFocus)
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tabWidget.setAcceptDrops(False)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setIconSize(QtCore.QSize(0, 20))
        self.tabWidget.setElideMode(QtCore.Qt.ElideRight)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_PersonalPage = QtWidgets.QWidget()
        self.tab_PersonalPage.setObjectName("tab_PersonalPage")
        self.lbl_surname1 = QtWidgets.QLabel(self.tab_PersonalPage)
        self.lbl_surname1.setGeometry(QtCore.QRect(160, 60, 91, 16))
        font = QtGui.QFont()
        font.setFamily("PT Serif")
        font.setPointSize(18)
        self.lbl_surname1.setFont(font)
        self.lbl_surname1.setObjectName("lbl_surname1")
        self.lbl_name1 = QtWidgets.QLabel(self.tab_PersonalPage)
        self.lbl_name1.setGeometry(QtCore.QRect(160, 90, 91, 16))
        font = QtGui.QFont()
        font.setFamily("PT Serif")
        font.setPointSize(18)
        self.lbl_name1.setFont(font)
        self.lbl_name1.setObjectName("lbl_name1")
        self.lbl_patr1 = QtWidgets.QLabel(self.tab_PersonalPage)
        self.lbl_patr1.setGeometry(QtCore.QRect(160, 120, 91, 16))
        font = QtGui.QFont()
        font.setFamily("PT Serif")
        font.setPointSize(18)
        self.lbl_patr1.setFont(font)
        self.lbl_patr1.setObjectName("lbl_patr1")
        self.lbl_birthday1 = QtWidgets.QLabel(self.tab_PersonalPage)
        self.lbl_birthday1.setGeometry(QtCore.QRect(160, 385, 141, 21))
        font = QtGui.QFont()
        font.setFamily("PT Serif")
        font.setPointSize(18)
        self.lbl_birthday1.setFont(font)
        self.lbl_birthday1.setObjectName("lbl_birthday1")
        self.lbl_phone1 = QtWidgets.QLabel(self.tab_PersonalPage)
        self.lbl_phone1.setGeometry(QtCore.QRect(160, 210, 141, 21))
        font = QtGui.QFont()
        font.setFamily("PT Serif")
        font.setPointSize(18)
        self.lbl_phone1.setFont(font)
        self.lbl_phone1.setObjectName("lbl_phone1")
        self.lbl_email1 = QtWidgets.QLabel(self.tab_PersonalPage)
        self.lbl_email1.setGeometry(QtCore.QRect(160, 245, 91, 16))
        font = QtGui.QFont()
        font.setFamily("PT Serif")
        font.setPointSize(18)
        self.lbl_email1.setFont(font)
        self.lbl_email1.setObjectName("lbl_email1")
        self.lbl_depnum1 = QtWidgets.QLabel(self.tab_PersonalPage)
        self.lbl_depnum1.setGeometry(QtCore.QRect(280, 10, 131, 21))
        font = QtGui.QFont()
        font.setFamily("PT Serif")
        font.setPointSize(18)
        self.lbl_depnum1.setFont(font)
        self.lbl_depnum1.setObjectName("lbl_depnum1")
        self.lbl_patr = QtWidgets.QLabel(self.tab_PersonalPage)
        self.lbl_patr.setGeometry(QtCore.QRect(290, 118, 291, 20))
        font = QtGui.QFont()
        font.setFamily("PT Serif")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_patr.setFont(font)
        self.lbl_patr.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_patr.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_patr.setObjectName("lbl_patr")
        self.lbl_phone = QtWidgets.QLabel(self.tab_PersonalPage)
        self.lbl_phone.setGeometry(QtCore.QRect(290, 210, 291, 20))
        font = QtGui.QFont()
        font.setFamily("PT Serif")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_phone.setFont(font)
        self.lbl_phone.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_phone.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_phone.setObjectName("lbl_phone")
        self.lbl_birthday = QtWidgets.QLabel(self.tab_PersonalPage)
        self.lbl_birthday.setGeometry(QtCore.QRect(290, 385, 291, 20))
        font = QtGui.QFont()
        font.setFamily("PT Serif")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_birthday.setFont(font)
        self.lbl_birthday.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_birthday.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_birthday.setObjectName("lbl_birthday")
        self.lbl_surname = QtWidgets.QLabel(self.tab_PersonalPage)
        self.lbl_surname.setGeometry(QtCore.QRect(290, 58, 291, 20))
        font = QtGui.QFont()
        font.setFamily("PT Serif")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_surname.setFont(font)
        self.lbl_surname.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_surname.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_surname.setObjectName("lbl_surname")
        self.lbl_email = QtWidgets.QLabel(self.tab_PersonalPage)
        self.lbl_email.setGeometry(QtCore.QRect(290, 243, 291, 20))
        font = QtGui.QFont()
        font.setFamily("PT Serif")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_email.setFont(font)
        self.lbl_email.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_email.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_email.setObjectName("lbl_email")
        self.lbl_name = QtWidgets.QLabel(self.tab_PersonalPage)
        self.lbl_name.setGeometry(QtCore.QRect(290, 88, 291, 20))
        font = QtGui.QFont()
        font.setFamily("PT Serif")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_name.setFont(font)
        self.lbl_name.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_name.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_name.setObjectName("lbl_name")
        self.lbl_depnum = QtWidgets.QLabel(self.tab_PersonalPage)
        self.lbl_depnum.setGeometry(QtCore.QRect(420, 10, 131, 21))
        font = QtGui.QFont()
        font.setFamily("PT Serif")
        font.setPointSize(18)
        self.lbl_depnum.setFont(font)
        self.lbl_depnum.setObjectName("lbl_depnum")
        icon = QtGui.QIcon.fromTheme("Lol")
        self.tabWidget.addTab(self.tab_PersonalPage, icon, "")
        self.tab_dialoga = QtWidgets.QWidget()
        self.tab_dialoga.setObjectName("tab_dialoga")
        icon = QtGui.QIcon.fromTheme("Lol")
        self.tabWidget.addTab(self.tab_dialoga, icon, "")
        self.tab_dialogs = QtWidgets.QWidget()
        self.tab_dialogs.setObjectName("tab_dialogs")
        self.tabWidget.addTab(self.tab_dialogs, "")
        self.tab_chat = QtWidgets.QWidget()
        self.tab_chat.setObjectName("tab_chat")
        self.tabWidget.addTab(self.tab_chat, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_surname1.setText(_translate("MainWindow", "Фамилия"))
        self.lbl_name1.setText(_translate("MainWindow", "Имя"))
        self.lbl_patr1.setText(_translate("MainWindow", "Отчество"))
        self.lbl_birthday1.setText(_translate("MainWindow", "Дата рождения"))
        self.lbl_phone1.setText(_translate("MainWindow", "Номер телефона"))
        self.lbl_email1.setText(_translate("MainWindow", "E-mail"))
        self.lbl_depnum1.setText(_translate("MainWindow", "Номер отдела"))
        self.lbl_patr.setText(_translate("MainWindow", "TextLabel"))
        self.lbl_phone.setText(_translate("MainWindow", "TextLabel"))
        self.lbl_birthday.setText(_translate("MainWindow", "TextLabel"))
        self.lbl_surname.setText(_translate("MainWindow", "TextLabel"))
        self.lbl_email.setText(_translate("MainWindow", "TextLabel"))
        self.lbl_name.setText(_translate("MainWindow", "TextLabel"))
        self.lbl_depnum.setText(_translate("MainWindow", "1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_PersonalPage), _translate("MainWindow", "ЛИЧНЫЙ КАБИНЕТ"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_dialoga), _translate("MainWindow", "СОТРУДНИКИ"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_dialogs), _translate("MainWindow", "Диалоги"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_chat), _translate("MainWindow", "Чат"))

